"""Add models for User, Fornecedor, Calendario, and Agendamento

Revision ID: 053ae587a162
Revises: 828c353ebbb3
Create Date: 2024-08-16 16:02:39.205655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053ae587a162'
down_revision = '828c353ebbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('hora', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('disponibilidade', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendario')
    op.drop_table('agenda')
    # ### end Alembic commands ###
