"""Atualizar backref em User e Agendamento

Revision ID: 828c353ebbb3
Revises: 9565382652cb
Create Date: 2024-08-16 16:00:01.008335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '828c353ebbb3'
down_revision = '9565382652cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendario')
    op.drop_table('agenda')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=300), nullable=True),
    sa.Column('hora', mysql.VARCHAR(collation='utf8_unicode_ci', length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('calendario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fornecedor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data_inicio', sa.DATE(), nullable=False),
    sa.Column('data_fim', sa.DATE(), nullable=False),
    sa.Column('disponibilidade', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], name='calendario_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
